# Generated by Django 3.2.6 on 2021-08-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('ciudad', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField()),
                ('colonia', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id_signos_vitales', models.AutoField(primary_key=True, serialize=False)),
                ('oxigeno', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('calorias_quemadas', models.FloatField()),
                ('peso_diario', models.FloatField()),
                ('distancia_recorrida', models.FloatField()),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.PROTECT, to='Doctors.persona')),
            ],
            options={
                'db_table': 'signos_vitales',
            },
        ),
        migrations.CreateModel(
            name='PersonaMedico',
            fields=[
                ('id_persona_medico', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_medica', models.CharField(max_length=50)),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.PROTECT, to='Doctors.persona')),
            ],
            options={
                'db_table': 'persona_medico',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_actual', models.DateField(blank=True, null=True)),
                ('id_signos_vitales', models.ForeignKey(db_column='id_signos_vitales', on_delete=django.db.models.deletion.PROTECT, to='Doctors.signosvitales')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
    ]
