# Generated by Django 3.2.6 on 2021-08-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_alter_persona_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='id_signos_vitales',
            field=models.ForeignKey(db_column='id_signos_vitales', on_delete=django.db.models.deletion.RESTRICT, to='Doctors.signosvitales'),
        ),
    ]
