# Generated by Django 3.2.6 on 2021-08-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_alter_historial_id_signos_vitales'),
    ]

    operations = [
        migrations.AddField(
            model_name='signosvitales',
            name='ritmo_cardiaco',
            field=models.FloatField(default=80),
            preserve_default=False,
        ),
    ]
