# Generated by Django 3.2.6 on 2021-08-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0006_alter_signosvitales_pasos_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='oxigeno',
            field=models.IntegerField(),
        ),
    ]
